name = "Gaylord"
author = "Memelord"
version = "Versionlord"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "229c6ee48c39a82fd05277db2a85aa417a0b7381cf3f6211d30b4ca8c2ae48b9"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
